# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Nusayer
tagline: Software Engineer • Teacher
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
lang: en
logo: /assets/icons/icon-512x512.png



# Build settings
#theme: jekyll-theme-hydejack
remote_theme: hydecorp/hydejack@v9
plugins:
  - jekyll-feed
  - jekyll-avatar
  - jekyll-seo-tag
  - jekyll-include-cache

# Sidebar image and theme color of the site.
accent_color: rgb(121, 112, 182)
accent_image: '/assets/images/image3.jpg'
theme_color:  '#342E4B'


google_fonts:          Roboto+Slab:700|Noto+Sans:400,400i,700,700i
font:                  Noto Sans, Helvetica, Arial, sans-serif
font_heading:          Roboto Slab, Helvetica, Arial, sans-serif
font_code:             Fira Code, Menlo, Monaco, Consolas, monospace;

author:
  picture: '/assets/images/image4.jpg'
  name: Nusayer Masud Siddique
  email: nusayermasud@gmail.com
  about: |
    Hi, I am Nusayer. I am a CS graduate from BRAC University. I have a huge passion for web/mobile development. During my undergrad years, I have done several java and flutter projects. I am also passionate about deep learning and machine learning. My undergraduate research work was about predicting seizures in epileptic patients, which was published at IEEE Region 10 Symposium (TENSYMP) conference. 
  social:
    email: mailto:nusayermasud@gmail.com
    twitter: nusayer_masud
    github: nusayer
    facebook: nusayermasudsiddique

menu:
  - title: About
    url: /about
  - title: Projects
    url: /project
  - title: Research
    url: /research
  - title: Resume
    url: /resume

copyright:             

hydejack:
 # Note that dark mode only works in the PRO version of Hydejack.
  dark_mode:
    # Set to `true` to always use the dark theme.
    always:            false

    # Set to `true` to use the dark theme based on visitors' local time.
    dynamic:           true
    sunrise:           6
    sunset:            18

    # Set to `true` to allow visitors to switch between light and dark mode.
    icon:              true
  # Set to true to disable the built-in search functionality.
  # Note that search is disabled during local use to save on build time.
  # Run Jekyll with the `JEKYLL_ENV` environment variable set to `production` to enable.
  no_search:           true

# Collections
# ========================================================================================

collections:
  featured_categories:
    permalink:         /blog/:name/
    output:            true

  featured_tags:
    permalink:         /tag-:name/
    output:            true

  projects:
    permalink:         /projects/:path/
    output:            true

